!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      rs435_JSON_file_path: ''
      rs435_color_auto_exposure_priority: false
      rs435_color_backlight_compensation: false
      rs435_color_brightness: 0
      rs435_color_contrast: 50
      rs435_color_enable_auto_exposure: true
      rs435_color_exposure: 166
      rs435_color_frames_queue_size: 16
      rs435_color_gain: 64
      rs435_color_gamma: 300
      rs435_color_hue: 0
      rs435_color_power_line_frequency: 3
      rs435_color_saturation: 64
      rs435_color_sharpness: 50
      rs435_color_white_balance: 460
      rs435_depth_emitter_enabled: 1
      rs435_depth_enable_auto_exposure: true
      rs435_depth_error_polling_enabled: false
      rs435_depth_exposure: 425
      rs435_depth_frames_queue_size: 16
      rs435_depth_gain: 16
      rs435_depth_laser_power: 12.0
      rs435_depth_output_trigger_enabled: false
      rs435_depth_units: 0.001
      rs435_depth_visual_preset: 3
      rs435_sensors_enabled: true
      state: true
      type: ''
    state: []
  rs435_JSON_file_path: ''
  rs435_color_auto_exposure_priority: false
  rs435_color_backlight_compensation: false
  rs435_color_brightness: 0
  rs435_color_contrast: 50
  rs435_color_enable_auto_exposure: true
  rs435_color_exposure: 166
  rs435_color_frames_queue_size: 16
  rs435_color_gain: 64
  rs435_color_gamma: 300
  rs435_color_hue: 0
  rs435_color_power_line_frequency: 3
  rs435_color_saturation: 64
  rs435_color_sharpness: 50
  rs435_color_white_balance: 460
  rs435_depth_emitter_enabled: 1
  rs435_depth_enable_auto_exposure: true
  rs435_depth_error_polling_enabled: false
  rs435_depth_exposure: 425
  rs435_depth_frames_queue_size: 16
  rs435_depth_gain: 16
  rs435_depth_laser_power: 12.0
  rs435_depth_output_trigger_enabled: false
  rs435_depth_units: 0.001
  rs435_depth_visual_preset: 3
  rs435_sensors_enabled: true
state: []
