yolo_model:

  config_file:
    name: yolov3-tiny-subT.cfg
  weight_file:
    name: yolov3-tiny-subT.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - Survivor
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - Backpack
      - Drill
      - none
      - none
      - Backpack
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - Drill
      - none
      - none
      - Fire Extinguisher
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - Cell Phone
      - Cell Phone
      - none
      - none
      - Cell Phone
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - Drill
      - Fire Extinguisher
