yolo_model:

  config_file:
    name: yolov3-tiny-subT.cfg
  weight_file:
    name: yolov3-tiny-subT_14200.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - survivor
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - backpack
      - none
      - none
      - none
      - backpack
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - fire extinguisher
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - phone
      - phone
      - none
      - none
      - phone
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - none
      - drill
      - fire extinguisher
